# Generated by Django 4.2.3 on 2023-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('employee_dept', models.CharField(max_length=100, null=True)),
                ('employee_contact', models.CharField(max_length=15, null=True)),
                ('employee_gender', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
