# Generated by Django 4.2.3 on 2023-09-23 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assettracking', '0003_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('checkout_condition', models.TextField()),
                ('return_condition', models.TextField()),
                ('checkout_datetime', models.DateTimeField(auto_now_add=True)),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettracking.employee')),
                ('serial_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assettracking.device')),
            ],
        ),
    ]
