# Generated by Django 4.2.3 on 2023-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettracking', '0004_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('checked_out', 'Checked Out'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
