# Generated by Django 4.2.3 on 2023-09-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettracking', '0005_allocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('available', 'Available')], default='available', max_length=20),
        ),
    ]
