# Generated by Django 4.2.3 on 2023-09-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assettracking', '0006_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
