# Generated by Django 4.2.3 on 2023-09-24 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assettracking', '0007_alter_company_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='serial_number',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='allocation',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
